export const FETCH_USER_REQUEST="FETCH_USER_REQUEST"
export const FETCH_USERS_SUCCESS="FETCH_USERS_SUCCESS"
export const FETCH_USERS_FAILURE=" FETCH_USERS_FAILURE"
export const RESET_USER_REQUEST="RESET_USER_REQUEST"